version: "3.9"
services:
  redis:
    container_name: redis
    image: redis:latest
    networks:
      - jyk
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
    command: redis-server --appendonly yes
  mysql:
    container_name: mysql
    image: mysql:latest
    networks:
      - jyk
    ports:
      - 3306:3306
    volumes:
      - ./mysql/var/lib/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_PASSWORD=jyk
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
networks:
  jyk:
